# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a46480372813a04ad344ab6570eb51333853eaa38e80498c2c5011cacebb1bf39144df0cdb6410924fc87e134513ff49b4305e7d745b3dbe4baa3f29148cfb31

test:
  secret_key_base: 05cab361f38564f7d5cbe0deeb0acb7d0e3cea9c3300ebf3195b79795eafbaf926586b16445d2ab4af73c7420f25126812d93476c8e3a7c36fc28c5b10319454

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
