# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 301b290ac3a5fd90871c559ae7a0063b71e8739b720148dc0c103d104d0327c3634b2f79fb61b9cad1b2036c6d5e0f3b704fd607b16674484a4a8d1e3fb936a2

test:
  secret_key_base: 0c676ce104eba155afa52b77c75d01f281f5d5a62e437758dec1d0a7974512e620c9e25db241c65b4bd1bd1ee40d6b7f7c8a61519c469da53da17d53947b3ca6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
